### PR TITLE
OSOE-1129: Fix styles and scripts give 404 when deployed

### LINKED ISSUE #40: Styles and scripts give 404 when deployed (OSOE-1129)
3rd party styles and scripts that come from the `node_modules` and are supposed to be in the `vendors` folder are missing.

Locally, they are working if you build the solution from VS. However, I think it's reproducible if you clean the repo and use `dotnet publish -c Release -o ./publish` to build the app, then use ILSpy to inspect the `.dll`s.

I detected this in multiple apps now.

### Repro:

- Update NodeJS to the latest version.
- Use a third-party script/style (like ˙prism.js` for example).
- Deploy the app.
- See that the scripts and stylings are missing.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-1129)

### PR DESCRIPTION
**Pull request by sarahelsaig**
[OSOE-1129](https://lombiq.atlassian.net/browse/OSOE-1129)
Fixes #40

[OSOE-1129]: https://lombiq.atlassian.net/browse/OSOE-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: CopyVendors.cs [hunk 1]
```diff
@@ -44,6 +47,14 @@ private void FindVendor(string projectPath, string targetBase, XElement vendor)
             targetBase,
             vendor.XPathSelectElement("./CopyTo")?.Value?.Trim() is { Length: > 0 } copyTo ? copyTo : name);
 
+        var patterns = vendor
+                .XPathSelectElements("./Pattern")
+                .Select(pattern => pattern.Value.Trim())
+                .Where(pattern => !string.IsNullOrEmpty(pattern))
+                .ToList() is { Count: > 0 } customPatterns
```
Comment (Piedone) [inline CopyVendors.cs]: image

File: Lombiq.Npm.Targets.csproj [hunk 2]
```diff
@@ -39,6 +39,7 @@
     <PackageReference Include="Microsoft.Build.Framework" Version="17.14.7" />
     <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.13.26" />
     <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.14.7" />
+    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.6" />
```
Comment (Piedone) [inline Lombiq.Npm.Targets.csproj]: A clean build under Windows fails for me in VS with this output.

[Build log.txt](https://github.com/user-attachments/files/21043476/Build.log.txt)

Note the repeated errors of this kind:

```
34>Lombiq.Hosting.Tenants.FeaturesGuard -> E:\ShortPath\OSOCE2\src\Modules\Lombiq.Hosting.Tenants\Lombiq.Hosting.Tenants.FeaturesGuard\bin\Debug\net8.0\Lombiq.Hosting.Tenants.FeaturesGuard.dll
47>E:\ShortPath\OSOCE2\src\Utilities\Lombiq.Npm.Targets\Lombiq.Npm.Targets.targets(80,5): error MSB4018: The "CopyVendors" task failed unexpectedly.
47>E:\ShortPath\OSOCE2\src\Utilities\Lombiq.Npm.Targets\Lombiq.Npm.Targets.targets(80,5): error MSB4018: System.IO.FileNotFoundException->Microsoft.Build.Framework.BuildException.GenericBuildTransferredException: Could not load file or assembly 'Microsoft.Extensions.FileSystemGlobbing, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
```

**Review by Piedone — CHANGES_REQUESTED** [review]

File: Lombiq.Npm.Targets.csproj (hunk 2 above)
Comment (sarahelsaig) [reply Lombiq.Npm.Targets.csproj]: [Mood.](https://www.youtube.com/watch?v=z3pPAsfdeUI)

Comment (sarahelsaig) [reply Lombiq.Npm.Targets.csproj]: It turns out we didn't actually need [this task order change](https://github.com/Lombiq/NPM-Targets/pull/41/files/f9f15ba5fcae9c664e9c20ed7d06e35bee116804#diff-df8f3f4a04a0bf6c1fb5815c3dd05bb792eb4d4408341837c4fb06bc8a2e7eb0L57-R58) and the solution was the `<EmbeddedResource>` entry alone by itself. Launching after the `AfterResolveReferences` target is needed to ensure the external package is loaded before the task is launched.

Comment (Piedone) [reply Lombiq.Npm.Targets.csproj]: Classic :D.

Comment (Piedone) [reply Lombiq.Npm.Targets.csproj]: I still get the same error.

Comment (sarahelsaig) [reply Lombiq.Npm.Targets.csproj]: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/1050#discussion_r2089559882

Comment (Piedone) [reply Lombiq.Npm.Targets.csproj]: This is not the same. That was a cosmetic error, being visible in the Error List but otherwise not bothering anything, and disappearing after a reopen of the solution.

This error is persistent and breaks the build, I can't run the app at all. It's also a different one, since this is due to the newly added `Microsoft.Extensions.FileSystemGlobbing` reference.

Comment (sarahelsaig) [reply Lombiq.Npm.Targets.csproj]: It's the same cause. It just manifests more severely because of the added NuGet package dependency. In both cases the problem is exclusive to Visual Studio and a build (clean or otherwise) works completely fine with `dotnet`, [even on Windows](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/16076497078/job/45372866343?pr=1088).

As the `<Pattern>` option was just a bonus I threw in to make things neater, my only course here is to revert those changes and open a new issue (#42) for this Visual Studio specific problem, before this improvement can be merged in. Since I don't own Windows any more, that will be a task for someone else to take on.

**Review by Piedone — APPROVED** [review]
